-- THIS FILE IS AUTO-GENERATED BY scripts/gen-main.rkt; DO NOT EDIT IT DIRECTLY.
import Pretty.Claims.MeasRender
import Pretty.Claims.Pareto
import Pretty.Claims.Render
import Pretty.Claims.ResolveDet
import Pretty.Claims.ResolveEfficient
import Pretty.Claims.ResolveOptimal
import Pretty.Claims.ResolveTotal
import Pretty.Claims.ResolveValid
import Pretty.Claims.Widen
import Pretty.Claims
import Pretty.Defs.Basic
import Pretty.Defs.Factory
import Pretty.Defs.Layout
import Pretty.Defs.MeasureSetOp
import Pretty.Defs.Resolve
import Pretty.Defs
import Pretty.Supports.Basic
import Pretty.Supports.Dedup
import Pretty.Supports.DocSize
import Pretty.Supports.Domination
import Pretty.Supports.FactoryMath
import Pretty.Supports.LastAndCost
import Pretty.Supports.Layout
import Pretty.Supports.LayoutCost
import Pretty.Supports.MeasRender
import Pretty.Supports.Merge
import Pretty.Supports.MergeBasic
import Pretty.Supports.Pareto
import Pretty.Supports.ResolveLast
import Pretty.Supports.ResolveOptimal
import Pretty.Supports.ResolvePareto
import Pretty.Supports
import Pretty.Tactic
/-!
# A pretty expressive printer

Use the left navigation sidebar to see all documentations under the `Pretty` module. In particular:

- Claimed results (theorems and lemmas) are in the submodule `Pretty.Claims`.
- Definitions are in the submodule `Pretty.Defs`
- Support lemmas are in the submodule `Pretty.Supports`
-/
