#lang racket

(define doc #<<EOF
/-!
# A pretty expressive printer

Use the left navigation sidebar to see all documentations under the `Pretty` module. In particular:

- Claimed results (theorems and lemmas) are in the submodule `Pretty.Claims`.
- Definitions are in the submodule `Pretty.Defs`
- Support lemmas are in the submodule `Pretty.Supports`
-/
EOF
  )

(with-output-to-file "Pretty.lean"
  #:exists 'replace
  (λ ()
    (displayln "-- THIS FILE IS AUTO-GENERATED BY scripts/gen-main.rkt; DO NOT EDIT IT DIRECTLY.")
    (for ([f (in-directory "Pretty")]
          #:when (path-has-extension? f ".lean"))
      (define path (string-replace (~a (path-replace-extension f "")) "/" "."))
      (printf "import ~a\n" path))
    (displayln doc)))
